"""add categories

Revision ID: 0475c8cd3667
Revises: e247dc90a08e
Create Date: 2025-11-08 15:37:15.003222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0475c8cd3667'
down_revision = 'e247dc90a08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['cat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cat_id')

    op.drop_table('category')
    # ### end Alembic commands ###
