"""Add role relationship

Revision ID: 06facfea8f3d
Revises: 65c8f286ec77
Create Date: 2025-11-04 21:05:47.502097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06facfea8f3d'
down_revision = '65c8f286ec77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
