"""Add roles tables

Revision ID: 65c8f286ec77
Revises: dffd688f4f5e
Create Date: 2025-11-03 22:36:49.289659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c8f286ec77'
down_revision = 'dffd688f4f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_roles'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
